# Generated by Django 6.1 on 2026-08-07 22:40

import config.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_invitecode_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('Sales', 'SALES'), ('Cost of Sales', 'COST_OF_SALES'), ('Expenses', 'EXPENSES'), ('Income Tax', 'INCOME_TAX'), ('Non-Current Assets', 'NON_CURRENT_ASSETS'), ('Current Assets', 'CURRENT_ASSETS'), ('Current Liabilities', 'CURRENT_LIABILITIES'), ('Non-Current Liabilities', 'NON_CURRENT_LIABILITIES'), ("Owner's Equity", 'OWNERS_EQUITY'), ('Other Incomes', 'OTHERS')], max_length=30)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('description', models.TextField(blank=True, default='')),
                ('opening_balance', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='users.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.account')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
    ]
