version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django_web
    volumes:
      - ./backend:/app
    ports:
      - "8002:8002"
    env_file:
      - backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.21
    container_name: django_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
