version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: django_backend
    env_file: backend/.env
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
    depends_on:
      - neo4j

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: angular_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/yourpassword
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
