# Generated by Django 6.1 on 2026-08-07 22:40

import config.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0004_invitecode_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('transaction_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer')], max_length=8)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('opening_balance_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='users.company')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('reconciliation_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('statement_balance', models.FloatField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=9)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banks.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliations', to='users.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
