# Generated by Django 6.1 on 2026-08-07 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('journals', '0001_initial'),
        ('users', '0004_invitecode_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='reconciled_lines',
            field=models.ManyToManyField(blank=True, related_name='reconciliations', to='journals.journalline'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='users.company'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
