# Generated by Django 6.1 on 2026-08-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_initial'),
        ('journals', '0001_initial'),
        ('payables', '0001_initial'),
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='receivables.customer'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='destination_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='banks.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='journals.journalentry'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='source_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='banks.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='payables.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together={('company', 'reference')},
        ),
    ]
