# Generated by Django 6.1 on 2026-08-07 22:40

import config.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banks', '0002_initial'),
        ('journals', '0001_initial'),
        ('users', '0004_invitecode_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('customer_type', models.CharField(choices=[('STUDENT', 'Student'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=6)),
                ('total_amount', models.FloatField(default=0.0)),
                ('amount_received', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ar_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_invoices', to='accounts.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='users.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='receivables.customer')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='journals.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='ARReceipt',
            fields=[
                ('receipt_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('receipt_date', models.DateField()),
                ('amount', models.FloatField()),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='banks.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='users.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_receipts', to='journals.journalentry')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='receivables.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('line_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.FloatField(default=1.0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('amount', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='users.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receivables.salesinvoice')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='accounts.account')),
            ],
        ),
    ]
