FROM python:3.12-slim

WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend /app

ENV PYTHONUNBUFFERED=1
# CMD ["/app/entrypoint.sh", "gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8002"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]
