# Generated by Django 6.1 on 2026-08-07 22:40

import config.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0004_invitecode_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('seq', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('year_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_years', to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('period_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_number', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_periods', to='users.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='journals.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entry_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=6)),
                ('entry_type', models.CharField(choices=[('MANUAL', 'Manual'), ('BANK_RECON', 'Bank Reconciliation'), ('AP_PAYMENT', 'AP Payment'), ('AR_RECEIPT', 'AR Receipt'), ('BANK_TRANSACTION', 'Bank Transaction')], default='MANUAL', max_length=20)),
                ('total_debit', models.FloatField(default=0.0)),
                ('total_credit', models.FloatField(default=0.0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='users.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='journals.accountingperiod')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'unique_together': {('company', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('line_id', models.CharField(default=config.ids.new_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='users.company')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journals.journalentry')),
            ],
        ),
    ]
