# Generated by Django 6.0.7 on 2026-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_invitecode_company_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Accountant', 'Accountant'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
    ]
